admin_gui:
  title: "Заявки на кастом. титулы (%page%/%max%)"
  item:
    display_name: " "
    lore:
      - " &x&5&A&D&9&F&B&l&n▍&f Заявка от &x&5&A&D&9&F&B%player%"
      - " &x&5&A&D&9&F&B&l▍ &fТитул: &x&5&A&D&9&F&B%title%"
      - ""
      - " &x&5&A&D&9&F&B[ЛКМ] &f- принять заявку"
      - " &x&5&A&D&9&F&B[ПКМ] &f- отклонить заявку"
      - " "
      - " &x&5&A&D&9&F&B▶ &fБудьте внимательны! Принимайте/отклоняйте заявку"
      - "    &fстрого по правилам создания кастомных титулов."
  buttons:
    prev:
      material: ARROW
      name: "&x&5&A&D&9&F&B◀ &fПредыдущая страница"
    next:
      material: ARROW
      name: "&fСледующая страница &x&5&A&D&9&F&B▶"
create:
  decor:
    1:
      material: CYAN_STAINED_GLASS_PANE
      name: " "
    2:
      material: ORANGE_STAINED_GLASS_PANE
      name: " "
pagination:
  previous: "&x&5&A&D&9&F&B◀ &fПредыдущая страница"
  next: "&fСледующая страница &x&5&A&D&9&F&B▶"
back: "&x&5&A&D&9&F&B◀ &fНазад"
messages:
  title_on_moderation: " &x&F&F&2&7&0&0▶ &fЭтот титул еще на модерации!"
  hover: "&x&5&A&D&9&F&B[ЛКМ] &f- Перейти по ссылке"
  error: "Неверное количество. Пожалуйста, введите число."
  chat: "&x&5&A&D&9&F&B ▶ &fНапишите свой титул в чат"
  pending: " &x&5&A&D&9&F&B▶ &fВаш титул отправлен на проверку администрации!"
  admin:
    approve: "&x&5&A&D&9&F&B ▶ &fТитул &x&5&A&D&9&F&Bодобрен"
    reject: "&x&5&A&D&9&F&B ▶ &fТитул &x&5&A&D&9&F&Bотклонен"
  create:
    chat: " &x&5&A&D&9&F&B▶ &fВведите желаемый титул в чат."
linkmessage:
  - "&r"
  - "&#00D8FF&l&n▍&f Информация и правила создания личного титула:"
  - "&#00D8FF&l&n▍&f       &6&nhttps://t.me/luckydev&f"
  - "&#00D8FF&l▍&f           &7(на ссылку можно нажать)"
  - "&r"
link: "https://t.me/luckydev"
home:
  decor:
    1:
      material: CYAN_STAINED_GLASS_PANE
      name: " "
    2:
      material: ORANGE_STAINED_GLASS_PANE
      name: " "
  titul_approved:
    name: " "
    lore:
      - " &x&5&A&D&9&F&B&l&n▍&f Титул: &x&5&A&D&9&F&B%titul%"
      - " &x&5&A&D&9&F&B&l&n▍&f Статус: &x&3&5&F&F&0&0✔ &fОдобрен"
      - " &x&5&A&D&9&F&B&l▍&f Дата выдачи: &x&5&A&D&9&F&B%time%"
      - " "
      - " &x&5&A&D&9&F&B[ЛКМ] &f- установить титул"
  titul_pending:
    name: " "
    lore:
      - " &x&5&A&D&9&F&B&l&n▍&f Титул: &x&5&A&D&9&F&B%titul%"
      - " &x&5&A&D&9&F&B&l▍&f Статус: &x&F&F&2&7&0&0✘ &fНа модерации"
      - " "
  clear:
    material: BARRIER
    name: "&x&F&F&2&7&0&0✘ &fУбрать титул в табе и чате"
  menu:
    material: ITEM_FRAME
    name: " &x&5&A&D&9&F&B❏ Меню создания титула ❏"
creategui:
  info:
    name: " &x&5&A&D&9&F&BИнформация для создания титулов"
    lore:
      - ""
      - " &x&5&A&D&9&F&B&l&n▍&f При нажатии на эту кнопку в чате"
      - " &x&5&A&D&9&F&B&l&n▍&f появится ссылка, где вы сможете ознакомиться"
      - " &x&5&A&D&9&F&B&l&n▍&f с правилами создания титула и также"
      - " &x&5&A&D&9&F&B&l▍&f с подробной инструкцией по созданию титула."
      - ""
      - " &x&5&A&D&9&F&B&l&n▍&f Ссылка кликабельна и откроет страничку в вашем"
      - " &x&5&A&D&9&F&B&l&n▍&f браузере. Вы также сможете скопировать ссылку"
      - " &x&5&A&D&9&F&B&l&n▍&f и вставить её в нужный браузер вручную."
      - " &x&5&A&D&9&F&B&l▍&f Не создавайте титул, пока не ознакомитесь!"
      - ""
    material: WRITABLE_BOOK
  allinfo:
    name: " &x&5&A&D&9&F&BОбщая информация"
    lore:
      - ""
      - " &x&5&A&D&9&F&B&l&n▍&f В этом меню можно ознакомиться со всей"
      - " &x&5&A&D&9&F&B&l&n▍&f необходимой информацией для создания титула"
      - " &x&5&A&D&9&F&B&l▍&f и самостоятельно создать личный титул."
      - ""
      - " &x&5&A&D&9&F&B&l&n▍&f Обратите внимание, что если вы допустите ошибку"
      - " &x&5&A&D&9&F&B&l&n▍&f или нарушите правило, то исправить, восстановить"
      - " &x&5&A&D&9&F&B&l▍&f или изменить будет невозможно! Будьте внимательны!"
      - ""
    material: BOOK
  create:
    material: PAPER
    name: " &x&5&A&D&9&F&BСоздать личный титул"
    lore:
      - ""
      - " &x&5&A&D&9&F&B&l&n▍&f Количество имеющихся жетонов для создания титула &x&5&A&D&9&F&B%amount%"
      - " &x&5&A&D&9&F&B&l&n▍&f После нажатия на эту кнопку, меню закроется, вам в чат"
      - " &x&5&A&D&9&F&B&l&n▍&f будет необходимо ввести желаемый титул. Пожалуйста,"
      - " &x&5&A&D&9&F&B&l▍&f внимательно ознакомьтесь с инструкцией и правилами."
      - ""